### ISSUE TITLE
Crash android 11 and google camera 8.0

### ISSUE THREAD

**Issue by thelittlefireman** [lukaspieper/Gcam-Services-Provider#10]
hi,
 with google camera 8.0 on a pixel 3a, i've got this crash : 

```
11-04 19:11:04.541 12319 12319 D nativeloader: classloader namespace configured for unbundled vendor apk. library_path=/data/app/~~qxjZYQwbeNYoIAul5iIxEA==/com.google.android.GoogleCamera-03Z89sQQ5IPXXtcSlOpclw==/lib/arm64:/data/app/~~qxjZYQwbeNYoIAul5iIxEA==/com.google.android.GoogleCamera-03Z89sQQ5IPXXtcSlOpclw==/base.apk!/lib/arm64-v8a:/data/app/~~qxjZYQwbeNYoIAul5iIxEA==/com.google.android.GoogleCamera-03Z89sQQ5IPXXtcSlOpclw==/split_config.arm64_v8a.apk!/lib/arm64-v8a:/data/app/~~qxjZYQwbeNYoIAul5iIxEA==/com.google.android.GoogleCamera-03Z89sQQ5IPXXtcSlOpclw==/split_config.en.apk!/lib/arm64-v8a:/data/app/~~qxjZYQwbeNYoIAul5iIxEA==/com.google.android.GoogleCamera-03Z89sQQ5IPXXtcSlOpclw==/split_config.xxhdpi.apk!/lib/arm64-v8a:/vendor/lib64
11-04 19:11:04.563 12319 12319 I PackageParser: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG020G_VN.apk: overlay ignored due to required system property: ro.boot.hardware.sku,ro.boot.hardware.coo with value: G020G,VN
11-04 19:11:04.571 12319 12319 I PackageParser: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG020H_VN.apk: overlay ignored due to required system property: ro.boot.hardware.sku,ro.boot.hardware.coo with value: G020H,VN
11-04 19:11:04.571 12319 12319 I PackageParser: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG020F_VN.apk: overlay ignored due to required system property: ro.boot.hardware.sku,ro.boot.hardware.coo with value: G020F,VN
11-04 19:11:04.575 12319 12319 I PackageParser: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG020G.apk: overlay ignored due to required system property: ro.boot.hardware.sku with value: G020G
11-04 19:11:04.578 12319 12319 I PackageParser: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG020E.apk: overlay ignored due to required system property: ro.boot.hardware.sku with value: G020E
11-04 19:11:04.579 12319 12319 I PackageParser: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG020E_VN.apk: overlay ignored due to required system property: ro.boot.hardware.sku,ro.boot.hardware.coo with value: G020E,VN
11-04 19:11:04.581 12319 12319 I PackageParser: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG020H.apk: overlay ignored due to required system property: ro.boot.hardware.sku with value: G020H
11-04 19:11:04.590 12319 12319 D NetworkSecurityConfig: No Network Security Config specified, using platform default
11-04 19:11:04.590 12319 12319 D NetworkSecurityConfig: No Network Security Config specified, using platform default
11-04 19:11:04.592 12319 12319 W id.GoogleCamera: type=1400 audit(0.0:5000): avc: granted { execute } for path="/data/app/~~qxjZYQwbeNYoIAul5iIxEA==/com.google.android.GoogleCamera-03Z89sQQ5IPXXtcSlOpclw==/split_config.arm64_v8a.apk" dev="dm-8" ino=91911 scontext=u:r:untrusted_app:s0:c117,c256,c512,c768 tcontext=u:object_r:apk_data_file:s0 tclass=file app=com.google.android.GoogleCamera
11-04 19:11:04.657 12319 12319 I SignatureCheck: Signature check ok
11-04 19:11:04.665 12319 12319 W CAM_SearchIndexProv: Called onCreate
11-04 19:11:04.677 12319 12319 D AndroidRuntime: Shutting down VM
11-04 19:11:04.678 12319 12319 E AndroidRuntime: FATAL EXCEPTION: main
11-04 19:11:04.678 12319 12319 E AndroidRuntime: Process: com.google.android.GoogleCamera, PID: 12319
11-04 19:11:04.678 12319 12319 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.google.android.gms.learning.internal.util.Application: java.lang.IllegalStateException: Cannot start the Google Camera on an unsupported device
11-04 19:11:04.678 12319 12319 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
11-04 19:11:04.678 12319 12319 E AndroidRuntime:        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
11-04 19:11:04.678 12319 12319 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
11-04 19:11:04.678 12319 12319 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
11-04 19:11:04.678 12319 12319 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
11-04 19:11:04.678 12319 12319 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7656)
11-04 19:11:04.678 12319 12319 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-04 19:11:04.678 12319 12319 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-04 19:11:04.678 12319 12319 E AndroidRuntime:        at com.android.internal.os.ExecInit.main(ExecInit.java:43)
11-04 19:11:04.678 12319 12319 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
11-04 19:11:04.678 12319 12319 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
11-04 19:11:04.678 12319 12319 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Cannot start the Google Camera on an unsupported device
11-04 19:11:04.678 12319 12319 E AndroidRuntime:        at com.google.android.apps.camera.legacy.app.app.CameraApp.onCreate(PG:124)
11-04 19:11:04.678 12319 12319 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
11-04 19:11:04.678 12319 12319 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
11-04 19:11:04.678 12319 12319 E AndroidRuntime:        ... 10 more
11-04 19:11:04.679 12319 12319 E AndroidRuntime: Error reporting crash
11-04 19:11:04.679 12319 12319 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
11-04 19:11:04.679 12319 12319 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
11-04 19:11:04.679 12319 12319 E AndroidRuntime:        at android.os.BinderProxy.transact(BinderProxy.java:540)
11-04 19:11:04.679 12319 12319 E AndroidRuntime:        at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:5182)
11-04 19:11:04.679 12319 12319 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:158)
11-04 19:11:04.679 12319 12319 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
11-04 19:11:04.679 12319 12319 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
11-04 19:11:04.679 12319 12319 E AndroidRuntime:        at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
11-04 19:11:04.679 12319 12319 I Process : Sending signal. PID: 12319 SIG: 9
11-04 19:11:04.701  1352  2581 I ActivityManager: Process com.google.android.GoogleCamera (pid 12319) has died: fg  TOP 
11-04 19:11:04.702  1075  1075 I Zygote  : Process 12319 exited due to signal 9 (Killed)
11-04 19:11:04.703  1352  1575 I libprocessgroup: Successfully killed process cgroup uid 10117 pid 12319 in 0ms
11-04 19:11:04.708  1352  1557 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10117; state: DISABLED
11-04 19:11:04.708  1352  1572 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10117; state: ENABLED
11-04 19:11:04.726  1075  1075 D Zygote  : Forked child process 12346
11-04 19:11:04.735 12346 12346 W Zygote  : Can't access app profile directory: /data_mirror/cur_profiles/0/com.google.android.GoogleCamera
11-04 19:11:04.742  1352  1572 I ActivityManager: Start proc 12346:com.google.android.GoogleCamera/u0a117 for top-activity {com.google.android.GoogleCamera/com.android.camera.CameraLauncher}
11-04 19:11:04.751 12346 12346 E id.GoogleCamer: Not starting debugger since process cannot load the jdwp agent.
11-04 19:11:04.857 12346 12346 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10117 <<<<<<
11-04 19:11:04.863 12346 12346 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.profilebootclasspath"
11-04 19:11:04.863 12346 12346 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.enable_apex_image"
11-04 19:11:04.863 12346 12346 I AndroidRuntime: Using default boot image
11-04 19:11:04.863 12346 12346 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.disable_lock_profiling"
11-04 19:11:04.863 12346 12346 I AndroidRuntime: Leaving lock profiling enabled
11-04 19:11:04.863 12346 12346 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.enable_generational_cc"
11-04 19:11:04.862 12346 12346 W id.GoogleCamera: type=1400 audit(0.0:5001): avc: denied { read } for name="u:object_r:device_config_runtime_native_boot_prop:s0" dev="tmpfs" ino=21555 scontext=u:r:untrusted_app:s0:c117,c256,c512,c768 tcontext=u:object_r:device_config_runtime_native_boot_prop:s0 tclass=file permissive=0 app=com.google.android.GoogleCamera
11-04 19:11:04.990 12346 12346 D com.google.android.GoogleCamera: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
11-04 19:11:04.990 12346 12346 D com.google.android.GoogleCamera: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt66l.dat
11-04 19:11:05.025 12346 12346 W com.google.android.GoogleCamera: JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
11-04 19:11:05.033 12346 12346 D AndroidRuntime: Calling main entry com.android.internal.os.ExecInit
11-04 19:11:05.035 12346 12346 D Zygote  : begin preload
11-04 19:11:05.035 12346 12346 I Zygote  : Calling ZygoteHooks.beginPreload()
11-04 19:11:05.041 12346 12346 I Zygote  : Preloading shared libraries...
11-04 19:11:05.155 12346 12346 I Zygote  : Called ZygoteHooks.endPreload()
11-04 19:11:05.176 12346 12346 I Zygote  : Installed AndroidKeyStoreProvider in 21ms.
11-04 19:11:05.176 12346 12346 D Zygote  : end preload
11-04 19:11:05.213 12346 12346 D nativeloader: classloader namespace configured for unbundled vendor apk. library_path=/data/app/~~qxjZYQwbeNYoIAul5iIxEA==/com.google.android.GoogleCamera-03Z89sQQ5IPXXtcSlOpclw==/lib/arm64:/data/app/~~qxjZYQwbeNYoIAul5iIxEA==/com.google.android.GoogleCamera-03Z89sQQ5IPXXtcSlOpclw==/base.apk!/lib/arm64-v8a:/data/app/~~qxjZYQwbeNYoIAul5iIxEA==/com.google.android.GoogleCamera-03Z89sQQ5IPXXtcSlOpclw==/split_config.arm64_v8a.apk!/lib/arm64-v8a:/data/app/~~qxjZYQwbeNYoIAul5iIxEA==/com.google.android.GoogleCamera-03Z89sQQ5IPXXtcSlOpclw==/split_config.en.apk!/lib/arm64-v8a:/data/app/~~qxjZYQwbeNYoIAul5iIxEA==/com.google.android.GoogleCamera-03Z89sQQ5IPXXtcSlOpclw==/split_config.xxhdpi.apk!/lib/arm64-v8a:/vendor/lib64
11-04 19:11:05.235 12346 12346 I PackageParser: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG020G_VN.apk: overlay ignored due to required system property: ro.boot.hardware.sku,ro.boot.hardware.coo with value: G020G,VN
11-04 19:11:05.243 12346 12346 I PackageParser: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG020H_VN.apk: overlay ignored due to required system property: ro.boot.hardware.sku,ro.boot.hardware.coo with value: G020H,VN
11-04 19:11:05.243 12346 12346 I PackageParser: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG020F_VN.apk: overlay ignored due to required system property: ro.boot.hardware.sku,ro.boot.hardware.coo with value: G020F,VN
11-04 19:11:05.248 12346 12346 I PackageParser: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG020G.apk: overlay ignored due to required system property: ro.boot.hardware.sku with value: G020G
11-04 19:11:05.251 12346 12346 I PackageParser: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG020E.apk: overlay ignored due to required system property: ro.boot.hardware.sku with value: G020E
11-04 19:11:05.252 12346 12346 I PackageParser: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG020E_VN.apk: overlay ignored due to required system property: ro.boot.hardware.sku,ro.boot.hardware.coo with value: G020E,VN
11-04 19:11:05.253 12346 12346 I PackageParser: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG020H.apk: overlay ignored due to required system property: ro.boot.hardware.sku with value: G020H
11-04 19:11:05.262 12346 12346 D NetworkSecurityConfig: No Network Security Config specified, using platform default
11-04 19:11:05.262 12346 12346 D NetworkSecurityConfig: No Network Security Config specified, using platform default
11-04 19:11:05.329 12346 12346 I SignatureCheck: Signature check ok
11-04 19:11:05.338 12346 12346 W CAM_SearchIndexProv: Called onCreat
```

**Comment by innir** [comment]
Isn't it just the problem that Gcam doesn't support your device?

```
11-04 19:11:04.678 [...] java.lang.IllegalStateException: Cannot start the Google Camera on an unsupported device
```

**Comment by thelittlefireman** [comment]
But why it would not be supported ? It's a pixel 3a (ie Google Phone)

**Comment by abaker** [comment]
I downloaded Google Camera from apkmirror to install on a Pixel 4a 5G

After adding `--force-queryable` (#6) I was able to install 7.5.108.332953030.

I also tried 8.0.101.339539880 (next version after 7.5.108.332953030) and 8.1.200.352609439 (latest) and got `IllegalStateException: Cannot start the Google Camera on an unsupported device` too

**Comment by lukaspieper** [comment]
I'm sorry I haven't replied here yet.

Please refer here to [this answer](https://github.com/lukaspieper/Gcam-Services-Provider/issues/22#issuecomment-814239882) of me, should be the same problem.
