### ISSUE TITLE
Info Request

### ISSUE THREAD

**Issue by blipk** [lukaspieper/Gcam-Services-Provider#30]
Thanks for the app, works great on my xiaomi device.
However I was not sure how else to get in contact and had a question about how this was developed.

I'd like to implement something similar for another app that depends on some play services APIs, however I'm not sure where to start to profile which APIs the app is using to figure out what needs to be implemented?

Apologies if this is a silly question, or not the right place, I am new to Android development.

Thanks.

**Comment by lukaspieper** [comment]
Hi, 

I'm glad to hear that the app is working for you.

> However I was not sure how else to get in contact and had a question about how this was developed.

Starting a _discussion_ would have been better but here we go, no problem.

> I'd like to implement something similar for another app that depends on some play services APIs, however I'm not sure where to start to profile which APIs the app is using to figure out what needs to be implemented?

You start by capturing the log of the app that is not working. The log will look like the snippet from issue #6. The following part is the exception:

```
10-07 14:42:02.497 10405 10405 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.google.android.apps.camera.legacy.app.app.CameraApp: java.lang.SecurityException: Failed to find provider com.google.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: Caused by: java.lang.SecurityException: Failed to find provider com.google.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2357)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2340)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2282)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:1229)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2627)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2615)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at lpr.b(PG:14)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at lpr.a(PG:69)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at lpr.a(PG:33)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at com.google.android.apps.camera.legacy.app.app.CameraApp.onCreate(PG:115)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	... 8 more
10-07 14:42:02.497 10405 10405 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at com.android.server.content.ContentService.registerContentObserver(ContentService.java:355)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at android.content.IContentService$Stub.onTransact(IContentService.java:482)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1154)
10-07 14:42:02.497 10405 10405 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:1123)
```
I was lucky that the error message was very descriptive:
```
Failed to find provider com.google.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority
```

Furthermore I knew that Gcam works with microg. So I searched the repository for part of the error message (`com.google.android.gsf.gservices`) and found it in the [manifest](https://github.com/microg/GmsCore/blob/ad12bd5de4970a6607a18e37707fab9f444593a7/play-services-core/src/main/AndroidManifest.xml#L178). From the manifest, you can then find the appropriate Java/Kotlin class.

Then I just had to create a stub for the API, which you can find in this repository.

Since this issue is off topic, I will close it now, but you can continue to reply and ask here.
